version: "3.9"

services:
  ssh-honeypot:
    build: .
    ports:
      - "22:22"
    volumes:
      - ./Honeypot-Data:/data
    restart: unless-stopped

  exporter:
    build: .
    command: python exporter.py
    ports:
      - "8000:8000"
    volumes:
      - ./Honeypot-Data:/data
    restart: unless-stopped
    depends_on:
      - ssh-honeypot

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    depends_on:
      - exporter

volumes:
  prometheus-data: